export const GET_SURVEY_ANSWERS = 'GET_SURVEY_ANSWERS';
export const ADD_SURVEY_ANSWERS = 'ADD_SURVEY_ANSWERS';
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';
